"""initial schema

Revision ID: 8468ddcaf78e
Revises: 
Create Date: 2026-06-04 10:17:13.274003
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8468ddcaf78e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'expert', 'custom', name='difficulty', native_enum=False, length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'paused', 'done', 'failed', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('arch_hash', sa.String(length=64), nullable=False),
    sa.Column('weights_uri', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('pt', 'onnx', name='modelformat', native_enum=False, length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('standard', 'ng', name='benchmarkmode', native_enum=False), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'expert', 'custom', name='difficulty', native_enum=False, length=16), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_clear_ms', sa.Float(), nullable=False),
    sa.Column('avg_3bvps', sa.Float(), nullable=False),
    sa.Column('guess_rate', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark_results')
    op.drop_table('models')
    op.drop_table('training_runs')
    # ### end Alembic commands ###
